- name: Copy join-command local file to remote host
  copy:
    src: join-command
    dest: /tmp/join-command.sh
    mode: a+rwx
    remote_src: no

- name: Initialize the worker node and join it to the cluster
  command: sh /tmp/join-command.sh
